package it.molinari.utility;

public enum ActionType {
	//autenticazione
	LOGIN_REQUEST,
	LOGIN_RESPONSE,
	
	REGISTRATION_REQUEST,
	REGISTRATION_RESPONSE,
	
	//gestione catalogo
	GET_ITEMS_REQUEST,
	GET_ITEMS_RESPONSE,
	
	ADD_ITEMS_REQUEST,
	ADD_ITEMS_RESPONSE,
	
	REMOVE_ITEMS_REQUEST,
	REMOVE_ITEMS_RESPONSE,
	
	SEARCH_ITEMS_REQUEST,
	SEARCH_ITEMS_RESPONSE,

	//prestiti
	BORROW_ITEM_REQUEST,
	BORROW_ITEM_RESPONSE,
	
	RETURN_ITEM_REQUEST,
	RETURN_ITEM_RESPONSE,

	GET_USER_LOANS_REQUEST,
	GET_USER_LOANS_RESPONSE,

	//errori
	ERROR_RESPONSE

}
