package it.molinari.server.enums;

public enum ActionType 
{
    // autenticazione
    LOGIN_REQUEST("LOGIN_REQUEST"),
    LOGIN_RESPONSE("LOGIN_RESPONSE"),
    
    REGISTRATION_REQUEST("REGISTRATION_REQUEST"),
    REGISTRATION_RESPONSE("REGISTRATION_RESPONSE"),
    
    // gestione catalogo - libri
    GET_BOOKS_REQUEST("GET_BOOKS_REQUEST"),
    GET_BOOKS_RESPONSE("GET_BOOKS_RESPONSE"),

    ADD_BOOK_REQUEST("ADD_BOOK_REQUEST"),
    ADD_BOOK_RESPONSE("ADD_BOOK_RESPONSE"),

    REMOVE_BOOK_REQUEST("REMOVE_BOOK_REQUEST"),
    REMOVE_BOOK_RESPONSE("REMOVE_BOOK_RESPONSE"),

    UPDATE_BOOK_REQUEST("UPDATE_BOOK_REQUEST"),
    UPDATE_BOOK_RESPONSE("UPDATE_BOOK_RESPONSE"),

    SEARCH_BOOK_REQUEST("SEARCH_BOOK_REQUEST"),
    SEARCH_BOOK_RESPONSE("SEARCH_BOOK_RESPONSE"),
    
    // riviste
    GET_MAGAZINES_REQUEST("GET_MAGAZINES_REQUEST"),
    GET_MAGAZINES_RESPONSE("GET_MAGAZINES_RESPONSE"),

    ADD_MAGAZINE_REQUEST("ADD_MAGAZINE_REQUEST"),
    ADD_MAGAZINE_RESPONSE("ADD_MAGAZINE_RESPONSE"),

    REMOVE_MAGAZINE_REQUEST("REMOVE_MAGAZINE_REQUEST"),
    REMOVE_MAGAZINE_RESPONSE("REMOVE_MAGAZINE_RESPONSE"),

    UPDATE_MAGAZINE_REQUEST("UPDATE_MAGAZINE_REQUEST"),
    UPDATE_MAGAZINE_RESPONSE("UPDATE_MAGAZINE_RESPONSE"),

    SEARCH_MAGAZINE_REQUEST("SEARCH_MAGAZINE_REQUEST"),
    SEARCH_MAGAZINE_RESPONSE("SEARCH_MAGAZINE_RESPONSE"),
    
    // multimedia
    GET_MULTIMEDIA_REQUEST("GET_MULTIMEDIA_REQUEST"),
    GET_MULTIMEDIA_RESPONSE("GET_MULTIMEDIA_RESPONSE"),

    ADD_MULTIMEDIA_REQUEST("ADD_MULTIMEDIA_REQUEST"),
    ADD_MULTIMEDIA_RESPONSE("ADD_MULTIMEDIA_RESPONSE"),

    REMOVE_MULTIMEDIA_REQUEST("REMOVE_MULTIMEDIA_REQUEST"),
    REMOVE_MULTIMEDIA_RESPONSE("REMOVE_MULTIMEDIA_RESPONSE"),

    UPDATE_MULTIMEDIA_REQUEST("UPDATE_MULTIMEDIA_REQUEST"),
    UPDATE_MULTIMEDIA_RESPONSE("UPDATE_MULTIMEDIA_RESPONSE"),

    SEARCH_MULTIMEDIA_REQUEST("SEARCH_MULTIMEDIA_REQUEST"),
    SEARCH_MULTIMEDIA_RESPONSE("SEARCH_MULTIMEDIA_RESPONSE"),

    // prestiti
    BORROW_ITEM_REQUEST("BORROW_ITEM_REQUEST"),
    BORROW_ITEM_RESPONSE("BORROW_ITEM_RESPONSE"),
    
    RETURN_ITEM_REQUEST("RETURN_ITEM_REQUEST"),
    RETURN_ITEM_RESPONSE("RETURN_ITEM_RESPONSE"),

    GET_USER_LOANS_REQUEST("GET_USER_LOANS_REQUEST"),
    GET_USER_LOANS_RESPONSE("GET_USER_LOANS_RESPONSE"),

    CHECK_BORROW_REQUEST("CHECK_BORROW_REQUEST"),
    CHECK_BORROW_RESPONSE("CHECK_BORROW_RESPONSE"),

    CHECK_AVAILABILITY_REQUEST("CHECK_AVAILABILITY_REQUEST"),
    CHECK_AVAILABILITY_RESPONSE("CHECK_AVAILABILITY_RESPONSE"),

    // errori
    ERROR_RESPONSE("ERROR_RESPONSE");

    private final String value;

    ActionType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
