package it.molinari.server.enums;

public enum ActionType 
{
    // autenticazione
    LOGIN_REQUEST("LOGIN_REQUEST"),
    LOGIN_RESPONSE("LOGIN_RESPONSE"),
    
    REGISTRATION_REQUEST("REGISTRATION_REQUEST"),
    REGISTRATION_RESPONSE("REGISTRATION_RESPONSE"),
    
    // gestione catalogo - libri
    GET_ITEMS_REQUEST("GET_BOOKS_REQUEST"),
    GET_ITEMS_RESPONSE("GET_BOOKS_RESPONSE"),

    ADD_ITEMS_REQUEST("ADD_BOOK_REQUEST"),
    ADD_ITEMS_RESPONSE("ADD_BOOK_RESPONSE"),

    REMOVE_ITEMS_REQUEST("REMOVE_BOOK_REQUEST"),
    REMOVE_ITEMS_RESPONSE("REMOVE_BOOK_RESPONSE"),

    SEARCH_ITEMS_REQUEST("SEARCH_BOOK_REQUEST"),
    SEARCH_ITEMS_RESPONSE("SEARCH_BOOK_RESPONSE"),
    

    // prestiti
    BORROW_ITEM_REQUEST("BORROW_ITEM_REQUEST"),
    BORROW_ITEM_RESPONSE("BORROW_ITEM_RESPONSE"),
    
    RETURN_ITEM_REQUEST("RETURN_ITEM_REQUEST"),
    RETURN_ITEM_RESPONSE("RETURN_ITEM_RESPONSE"),

    GET_USER_LOANS_REQUEST("GET_USER_LOANS_REQUEST"),
    GET_USER_LOANS_RESPONSE("GET_USER_LOANS_RESPONSE"),

    // errori
    ERROR_RESPONSE("ERROR_RESPONSE");

    private final String value;

    ActionType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
